name: Take screenshots

on:
  push:
  workflow_dispatch:
  # ref: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    #- cron: '15 * * * *' # every minute 15 of every hour of every day
    - cron: '*/5 * * * *' # every 5 minute (shortest interval) of every hour of every day

jobs:
  shot-scraper:
    runs-on: ubuntu-latest
    if: ${{ github.repository != 'simonw/shot-scraper-template' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache Playwright browsers
        uses: actions/cache@v2
        with:
          path: ~/.cache/ms-playwright/
          key: ${{ runner.os }}-browsers
      - name: Upgrade pip (if any)
        run: |
          pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install Playwright dependencies
        run: |
          shot-scraper install
      - uses: actions/github-script@v6
        name: Create shots.yml if missing on first run
        with:
          script: |
            const fs = require('fs');
            if (!fs.existsSync('shots.yml')) {
                const desc = context.payload.repository.description;
                let line = '';
                if (desc && (desc.startsWith('http://') || desc.startsWith('https://'))) {
                    line = `- url: ${desc}` + '\n  output: shot.png\n  height: 800';
                } else {
                    line = '# - url: https://www.example.com/\n#   output: shot.png\n#   height: 800';
                }
                fs.writeFileSync('shots.yml', line + '\n');
            }
      - name: Take shots
        run: |
          shot-scraper multi shots.yml
      #- name: Scrape data with JS
      #  run: |
      #    shot-scraper javascript \
      #    https://store.sony.com.my/collections/playstation-5-console "({ \
      #      result: document.querySelector('.box__content').innerText === 'Oops! Something has gone wrong.\nReturn To Home Page', \
      #      timestamp: new Date().toLocaleDateString('en-us', { year: 'numeric', month: 'long', day: 'numeric' }) \
      #    })" > data.json
      - name: Scrape data with JS (file)
        run: |
          shot-scraper javascript \
          https://store.sony.com.my/collections/playstation-5-console \
          -i scrape.js -o data.json
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "${timestamp}" || exit 0
          git pull --rebase
          git push
